DROP TABLE IF EXISTS oauth_sessions;
DROP TABLE IF EXISTS settings;
DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS providers;
DROP TABLE IF EXISTS users;
