ALTER TABLE requests
    ADD COLUMN IF NOT EXISTS response_time INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS prompt_tokens INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS completion_tokens INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_tokens INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS cost DECIMAL(10,6) NOT NULL DEFAULT 0.000000;
