// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q            = new(Query)
	APIKey       *aPIKey
	Log          *log
	Model        *model
	OauthSession *oauthSession
	Provider     *provider
	Request      *request
	Setting      *setting
	User         *user
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	APIKey = &Q.APIKey
	Log = &Q.Log
	Model = &Q.Model
	OauthSession = &Q.OauthSession
	Provider = &Q.Provider
	Request = &Q.Request
	Setting = &Q.Setting
	User = &Q.User
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		APIKey:       newAPIKey(db, opts...),
		Log:          newLog(db, opts...),
		Model:        newModel(db, opts...),
		OauthSession: newOauthSession(db, opts...),
		Provider:     newProvider(db, opts...),
		Request:      newRequest(db, opts...),
		Setting:      newSetting(db, opts...),
		User:         newUser(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	APIKey       aPIKey
	Log          log
	Model        model
	OauthSession oauthSession
	Provider     provider
	Request      request
	Setting      setting
	User         user
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		APIKey:       q.APIKey.clone(db),
		Log:          q.Log.clone(db),
		Model:        q.Model.clone(db),
		OauthSession: q.OauthSession.clone(db),
		Provider:     q.Provider.clone(db),
		Request:      q.Request.clone(db),
		Setting:      q.Setting.clone(db),
		User:         q.User.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		APIKey:       q.APIKey.replaceDB(db),
		Log:          q.Log.replaceDB(db),
		Model:        q.Model.replaceDB(db),
		OauthSession: q.OauthSession.replaceDB(db),
		Provider:     q.Provider.replaceDB(db),
		Request:      q.Request.replaceDB(db),
		Setting:      q.Setting.replaceDB(db),
		User:         q.User.replaceDB(db),
	}
}

type queryCtx struct {
	APIKey       *aPIKeyDo
	Log          *logDo
	Model        *modelDo
	OauthSession *oauthSessionDo
	Provider     *providerDo
	Request      *requestDo
	Setting      *settingDo
	User         *userDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		APIKey:       q.APIKey.WithContext(ctx),
		Log:          q.Log.WithContext(ctx),
		Model:        q.Model.WithContext(ctx),
		OauthSession: q.OauthSession.WithContext(ctx),
		Provider:     q.Provider.WithContext(ctx),
		Request:      q.Request.WithContext(ctx),
		Setting:      q.Setting.WithContext(ctx),
		User:         q.User.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
