// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fdddf/openproxy/internal/models"
)

func newOauthSession(db *gorm.DB, opts ...gen.DOOption) oauthSession {
	_oauthSession := oauthSession{}

	_oauthSession.oauthSessionDo.UseDB(db, opts...)
	_oauthSession.oauthSessionDo.UseModel(&models.OauthSession{})

	tableName := _oauthSession.oauthSessionDo.TableName()
	_oauthSession.ALL = field.NewAsterisk(tableName)
	_oauthSession.ID = field.NewUint(tableName, "id")
	_oauthSession.CreatedAt = field.NewTime(tableName, "created_at")
	_oauthSession.UpdatedAt = field.NewTime(tableName, "updated_at")
	_oauthSession.DeletedAt = field.NewField(tableName, "deleted_at")
	_oauthSession.SessionID = field.NewString(tableName, "session_id")
	_oauthSession.ProviderID = field.NewUint(tableName, "provider_id")
	_oauthSession.State = field.NewString(tableName, "state")
	_oauthSession.CodeVerifier = field.NewString(tableName, "code_verifier")
	_oauthSession.CodeChallenge = field.NewString(tableName, "code_challenge")
	_oauthSession.CodeChallengeMethod = field.NewString(tableName, "code_challenge_method")
	_oauthSession.ExpiresAt = field.NewTime(tableName, "expires_at")

	_oauthSession.fillFieldMap()

	return _oauthSession
}

type oauthSession struct {
	oauthSessionDo

	ALL                 field.Asterisk
	ID                  field.Uint
	CreatedAt           field.Time
	UpdatedAt           field.Time
	DeletedAt           field.Field
	SessionID           field.String
	ProviderID          field.Uint
	State               field.String
	CodeVerifier        field.String
	CodeChallenge       field.String
	CodeChallengeMethod field.String
	ExpiresAt           field.Time

	fieldMap map[string]field.Expr
}

func (o oauthSession) Table(newTableName string) *oauthSession {
	o.oauthSessionDo.UseTable(newTableName)
	return o.updateTableName(newTableName)
}

func (o oauthSession) As(alias string) *oauthSession {
	o.oauthSessionDo.DO = *(o.oauthSessionDo.As(alias).(*gen.DO))
	return o.updateTableName(alias)
}

func (o *oauthSession) updateTableName(table string) *oauthSession {
	o.ALL = field.NewAsterisk(table)
	o.ID = field.NewUint(table, "id")
	o.CreatedAt = field.NewTime(table, "created_at")
	o.UpdatedAt = field.NewTime(table, "updated_at")
	o.DeletedAt = field.NewField(table, "deleted_at")
	o.SessionID = field.NewString(table, "session_id")
	o.ProviderID = field.NewUint(table, "provider_id")
	o.State = field.NewString(table, "state")
	o.CodeVerifier = field.NewString(table, "code_verifier")
	o.CodeChallenge = field.NewString(table, "code_challenge")
	o.CodeChallengeMethod = field.NewString(table, "code_challenge_method")
	o.ExpiresAt = field.NewTime(table, "expires_at")

	o.fillFieldMap()

	return o
}

func (o *oauthSession) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := o.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (o *oauthSession) fillFieldMap() {
	o.fieldMap = make(map[string]field.Expr, 11)
	o.fieldMap["id"] = o.ID
	o.fieldMap["created_at"] = o.CreatedAt
	o.fieldMap["updated_at"] = o.UpdatedAt
	o.fieldMap["deleted_at"] = o.DeletedAt
	o.fieldMap["session_id"] = o.SessionID
	o.fieldMap["provider_id"] = o.ProviderID
	o.fieldMap["state"] = o.State
	o.fieldMap["code_verifier"] = o.CodeVerifier
	o.fieldMap["code_challenge"] = o.CodeChallenge
	o.fieldMap["code_challenge_method"] = o.CodeChallengeMethod
	o.fieldMap["expires_at"] = o.ExpiresAt
}

func (o oauthSession) clone(db *gorm.DB) oauthSession {
	o.oauthSessionDo.ReplaceConnPool(db.Statement.ConnPool)
	return o
}

func (o oauthSession) replaceDB(db *gorm.DB) oauthSession {
	o.oauthSessionDo.ReplaceDB(db)
	return o
}

type oauthSessionDo struct{ gen.DO }

func (o oauthSessionDo) Debug() *oauthSessionDo {
	return o.withDO(o.DO.Debug())
}

func (o oauthSessionDo) WithContext(ctx context.Context) *oauthSessionDo {
	return o.withDO(o.DO.WithContext(ctx))
}

func (o oauthSessionDo) ReadDB() *oauthSessionDo {
	return o.Clauses(dbresolver.Read)
}

func (o oauthSessionDo) WriteDB() *oauthSessionDo {
	return o.Clauses(dbresolver.Write)
}

func (o oauthSessionDo) Session(config *gorm.Session) *oauthSessionDo {
	return o.withDO(o.DO.Session(config))
}

func (o oauthSessionDo) Clauses(conds ...clause.Expression) *oauthSessionDo {
	return o.withDO(o.DO.Clauses(conds...))
}

func (o oauthSessionDo) Returning(value interface{}, columns ...string) *oauthSessionDo {
	return o.withDO(o.DO.Returning(value, columns...))
}

func (o oauthSessionDo) Not(conds ...gen.Condition) *oauthSessionDo {
	return o.withDO(o.DO.Not(conds...))
}

func (o oauthSessionDo) Or(conds ...gen.Condition) *oauthSessionDo {
	return o.withDO(o.DO.Or(conds...))
}

func (o oauthSessionDo) Select(conds ...field.Expr) *oauthSessionDo {
	return o.withDO(o.DO.Select(conds...))
}

func (o oauthSessionDo) Where(conds ...gen.Condition) *oauthSessionDo {
	return o.withDO(o.DO.Where(conds...))
}

func (o oauthSessionDo) Order(conds ...field.Expr) *oauthSessionDo {
	return o.withDO(o.DO.Order(conds...))
}

func (o oauthSessionDo) Distinct(cols ...field.Expr) *oauthSessionDo {
	return o.withDO(o.DO.Distinct(cols...))
}

func (o oauthSessionDo) Omit(cols ...field.Expr) *oauthSessionDo {
	return o.withDO(o.DO.Omit(cols...))
}

func (o oauthSessionDo) Join(table schema.Tabler, on ...field.Expr) *oauthSessionDo {
	return o.withDO(o.DO.Join(table, on...))
}

func (o oauthSessionDo) LeftJoin(table schema.Tabler, on ...field.Expr) *oauthSessionDo {
	return o.withDO(o.DO.LeftJoin(table, on...))
}

func (o oauthSessionDo) RightJoin(table schema.Tabler, on ...field.Expr) *oauthSessionDo {
	return o.withDO(o.DO.RightJoin(table, on...))
}

func (o oauthSessionDo) Group(cols ...field.Expr) *oauthSessionDo {
	return o.withDO(o.DO.Group(cols...))
}

func (o oauthSessionDo) Having(conds ...gen.Condition) *oauthSessionDo {
	return o.withDO(o.DO.Having(conds...))
}

func (o oauthSessionDo) Limit(limit int) *oauthSessionDo {
	return o.withDO(o.DO.Limit(limit))
}

func (o oauthSessionDo) Offset(offset int) *oauthSessionDo {
	return o.withDO(o.DO.Offset(offset))
}

func (o oauthSessionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *oauthSessionDo {
	return o.withDO(o.DO.Scopes(funcs...))
}

func (o oauthSessionDo) Unscoped() *oauthSessionDo {
	return o.withDO(o.DO.Unscoped())
}

func (o oauthSessionDo) Create(values ...*models.OauthSession) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Create(values)
}

func (o oauthSessionDo) CreateInBatches(values []*models.OauthSession, batchSize int) error {
	return o.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (o oauthSessionDo) Save(values ...*models.OauthSession) error {
	if len(values) == 0 {
		return nil
	}
	return o.DO.Save(values)
}

func (o oauthSessionDo) First() (*models.OauthSession, error) {
	if result, err := o.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.OauthSession), nil
	}
}

func (o oauthSessionDo) Take() (*models.OauthSession, error) {
	if result, err := o.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.OauthSession), nil
	}
}

func (o oauthSessionDo) Last() (*models.OauthSession, error) {
	if result, err := o.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.OauthSession), nil
	}
}

func (o oauthSessionDo) Find() ([]*models.OauthSession, error) {
	result, err := o.DO.Find()
	return result.([]*models.OauthSession), err
}

func (o oauthSessionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.OauthSession, err error) {
	buf := make([]*models.OauthSession, 0, batchSize)
	err = o.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (o oauthSessionDo) FindInBatches(result *[]*models.OauthSession, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return o.DO.FindInBatches(result, batchSize, fc)
}

func (o oauthSessionDo) Attrs(attrs ...field.AssignExpr) *oauthSessionDo {
	return o.withDO(o.DO.Attrs(attrs...))
}

func (o oauthSessionDo) Assign(attrs ...field.AssignExpr) *oauthSessionDo {
	return o.withDO(o.DO.Assign(attrs...))
}

func (o oauthSessionDo) Joins(fields ...field.RelationField) *oauthSessionDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Joins(_f))
	}
	return &o
}

func (o oauthSessionDo) Preload(fields ...field.RelationField) *oauthSessionDo {
	for _, _f := range fields {
		o = *o.withDO(o.DO.Preload(_f))
	}
	return &o
}

func (o oauthSessionDo) FirstOrInit() (*models.OauthSession, error) {
	if result, err := o.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.OauthSession), nil
	}
}

func (o oauthSessionDo) FirstOrCreate() (*models.OauthSession, error) {
	if result, err := o.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.OauthSession), nil
	}
}

func (o oauthSessionDo) FindByPage(offset int, limit int) (result []*models.OauthSession, count int64, err error) {
	result, err = o.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = o.Offset(-1).Limit(-1).Count()
	return
}

func (o oauthSessionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = o.Count()
	if err != nil {
		return
	}

	err = o.Offset(offset).Limit(limit).Scan(result)
	return
}

func (o oauthSessionDo) Scan(result interface{}) (err error) {
	return o.DO.Scan(result)
}

func (o oauthSessionDo) Delete(models ...*models.OauthSession) (result gen.ResultInfo, err error) {
	return o.DO.Delete(models)
}

func (o *oauthSessionDo) withDO(do gen.Dao) *oauthSessionDo {
	o.DO = *do.(*gen.DO)
	return o
}
