// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fdddf/openproxy/internal/models"
)

func newProvider(db *gorm.DB, opts ...gen.DOOption) provider {
	_provider := provider{}

	_provider.providerDo.UseDB(db, opts...)
	_provider.providerDo.UseModel(&models.Provider{})

	tableName := _provider.providerDo.TableName()
	_provider.ALL = field.NewAsterisk(tableName)
	_provider.ID = field.NewUint(tableName, "id")
	_provider.CreatedAt = field.NewTime(tableName, "created_at")
	_provider.UpdatedAt = field.NewTime(tableName, "updated_at")
	_provider.DeletedAt = field.NewField(tableName, "deleted_at")
	_provider.Name = field.NewString(tableName, "name")
	_provider.Platform = field.NewString(tableName, "platform")
	_provider.ApiKey = field.NewString(tableName, "api_key")
	_provider.BaseURL = field.NewString(tableName, "base_url")
	_provider.ProxyURL = field.NewString(tableName, "proxy_url")
	_provider.IsActive = field.NewBool(tableName, "is_active")
	_provider.ClientID = field.NewString(tableName, "client_id")
	_provider.ClientSecret = field.NewString(tableName, "client_secret")
	_provider.AccessToken = field.NewString(tableName, "access_token")
	_provider.RefreshToken = field.NewString(tableName, "refresh_token")
	_provider.TokenExpiry = field.NewTime(tableName, "token_expiry")
	_provider.AuthURL = field.NewString(tableName, "auth_url")
	_provider.TokenURL = field.NewString(tableName, "token_url")
	_provider.RedirectURL = field.NewString(tableName, "redirect_url")
	_provider.Scopes_ = field.NewString(tableName, "scopes")
	_provider.AccountID = field.NewString(tableName, "account_id")
	_provider.HealthCheckEnabled = field.NewBool(tableName, "health_check_enabled")
	_provider.HealthCheckStatus = field.NewString(tableName, "health_check_status")
	_provider.HealthCheckChecked = field.NewTime(tableName, "health_check_checked")

	_provider.fillFieldMap()

	return _provider
}

type provider struct {
	providerDo

	ALL                field.Asterisk
	ID                 field.Uint
	CreatedAt          field.Time
	UpdatedAt          field.Time
	DeletedAt          field.Field
	Name               field.String
	Platform           field.String
	ApiKey             field.String
	BaseURL            field.String
	ProxyURL           field.String
	IsActive           field.Bool
	ClientID           field.String
	ClientSecret       field.String
	AccessToken        field.String
	RefreshToken       field.String
	TokenExpiry        field.Time
	AuthURL            field.String
	TokenURL           field.String
	RedirectURL        field.String
	Scopes_            field.String
	AccountID          field.String
	HealthCheckEnabled field.Bool
	HealthCheckStatus  field.String
	HealthCheckChecked field.Time

	fieldMap map[string]field.Expr
}

func (p provider) Table(newTableName string) *provider {
	p.providerDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p provider) As(alias string) *provider {
	p.providerDo.DO = *(p.providerDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *provider) updateTableName(table string) *provider {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.Name = field.NewString(table, "name")
	p.Platform = field.NewString(table, "platform")
	p.ApiKey = field.NewString(table, "api_key")
	p.BaseURL = field.NewString(table, "base_url")
	p.ProxyURL = field.NewString(table, "proxy_url")
	p.IsActive = field.NewBool(table, "is_active")
	p.ClientID = field.NewString(table, "client_id")
	p.ClientSecret = field.NewString(table, "client_secret")
	p.AccessToken = field.NewString(table, "access_token")
	p.RefreshToken = field.NewString(table, "refresh_token")
	p.TokenExpiry = field.NewTime(table, "token_expiry")
	p.AuthURL = field.NewString(table, "auth_url")
	p.TokenURL = field.NewString(table, "token_url")
	p.RedirectURL = field.NewString(table, "redirect_url")
	p.Scopes_ = field.NewString(table, "scopes")
	p.AccountID = field.NewString(table, "account_id")
	p.HealthCheckEnabled = field.NewBool(table, "health_check_enabled")
	p.HealthCheckStatus = field.NewString(table, "health_check_status")
	p.HealthCheckChecked = field.NewTime(table, "health_check_checked")

	p.fillFieldMap()

	return p
}

func (p *provider) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *provider) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 23)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["name"] = p.Name
	p.fieldMap["platform"] = p.Platform
	p.fieldMap["api_key"] = p.ApiKey
	p.fieldMap["base_url"] = p.BaseURL
	p.fieldMap["proxy_url"] = p.ProxyURL
	p.fieldMap["is_active"] = p.IsActive
	p.fieldMap["client_id"] = p.ClientID
	p.fieldMap["client_secret"] = p.ClientSecret
	p.fieldMap["access_token"] = p.AccessToken
	p.fieldMap["refresh_token"] = p.RefreshToken
	p.fieldMap["token_expiry"] = p.TokenExpiry
	p.fieldMap["auth_url"] = p.AuthURL
	p.fieldMap["token_url"] = p.TokenURL
	p.fieldMap["redirect_url"] = p.RedirectURL
	p.fieldMap["scopes"] = p.Scopes_
	p.fieldMap["account_id"] = p.AccountID
	p.fieldMap["health_check_enabled"] = p.HealthCheckEnabled
	p.fieldMap["health_check_status"] = p.HealthCheckStatus
	p.fieldMap["health_check_checked"] = p.HealthCheckChecked
}

func (p provider) clone(db *gorm.DB) provider {
	p.providerDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p provider) replaceDB(db *gorm.DB) provider {
	p.providerDo.ReplaceDB(db)
	return p
}

type providerDo struct{ gen.DO }

func (p providerDo) Debug() *providerDo {
	return p.withDO(p.DO.Debug())
}

func (p providerDo) WithContext(ctx context.Context) *providerDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p providerDo) ReadDB() *providerDo {
	return p.Clauses(dbresolver.Read)
}

func (p providerDo) WriteDB() *providerDo {
	return p.Clauses(dbresolver.Write)
}

func (p providerDo) Session(config *gorm.Session) *providerDo {
	return p.withDO(p.DO.Session(config))
}

func (p providerDo) Clauses(conds ...clause.Expression) *providerDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p providerDo) Returning(value interface{}, columns ...string) *providerDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p providerDo) Not(conds ...gen.Condition) *providerDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p providerDo) Or(conds ...gen.Condition) *providerDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p providerDo) Select(conds ...field.Expr) *providerDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p providerDo) Where(conds ...gen.Condition) *providerDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p providerDo) Order(conds ...field.Expr) *providerDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p providerDo) Distinct(cols ...field.Expr) *providerDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p providerDo) Omit(cols ...field.Expr) *providerDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p providerDo) Join(table schema.Tabler, on ...field.Expr) *providerDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p providerDo) LeftJoin(table schema.Tabler, on ...field.Expr) *providerDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p providerDo) RightJoin(table schema.Tabler, on ...field.Expr) *providerDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p providerDo) Group(cols ...field.Expr) *providerDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p providerDo) Having(conds ...gen.Condition) *providerDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p providerDo) Limit(limit int) *providerDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p providerDo) Offset(offset int) *providerDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p providerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *providerDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p providerDo) Unscoped() *providerDo {
	return p.withDO(p.DO.Unscoped())
}

func (p providerDo) Create(values ...*models.Provider) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p providerDo) CreateInBatches(values []*models.Provider, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p providerDo) Save(values ...*models.Provider) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p providerDo) First() (*models.Provider, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Provider), nil
	}
}

func (p providerDo) Take() (*models.Provider, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Provider), nil
	}
}

func (p providerDo) Last() (*models.Provider, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Provider), nil
	}
}

func (p providerDo) Find() ([]*models.Provider, error) {
	result, err := p.DO.Find()
	return result.([]*models.Provider), err
}

func (p providerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Provider, err error) {
	buf := make([]*models.Provider, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p providerDo) FindInBatches(result *[]*models.Provider, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p providerDo) Attrs(attrs ...field.AssignExpr) *providerDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p providerDo) Assign(attrs ...field.AssignExpr) *providerDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p providerDo) Joins(fields ...field.RelationField) *providerDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p providerDo) Preload(fields ...field.RelationField) *providerDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p providerDo) FirstOrInit() (*models.Provider, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Provider), nil
	}
}

func (p providerDo) FirstOrCreate() (*models.Provider, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Provider), nil
	}
}

func (p providerDo) FindByPage(offset int, limit int) (result []*models.Provider, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p providerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p providerDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p providerDo) Delete(models ...*models.Provider) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *providerDo) withDO(do gen.Dao) *providerDo {
	p.DO = *do.(*gen.DO)
	return p
}
