// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/fdddf/openproxy/internal/models"
)

func newRequest(db *gorm.DB, opts ...gen.DOOption) request {
	_request := request{}

	_request.requestDo.UseDB(db, opts...)
	_request.requestDo.UseModel(&models.Request{})

	tableName := _request.requestDo.TableName()
	_request.ALL = field.NewAsterisk(tableName)
	_request.ID = field.NewUint(tableName, "id")
	_request.CreatedAt = field.NewTime(tableName, "created_at")
	_request.UpdatedAt = field.NewTime(tableName, "updated_at")
	_request.DeletedAt = field.NewField(tableName, "deleted_at")
	_request.Method = field.NewString(tableName, "method")
	_request.Path = field.NewString(tableName, "path")
	_request.RequestHeaders = field.NewString(tableName, "request_headers")
	_request.RequestBody = field.NewString(tableName, "request_body")
	_request.ResponseHeaders = field.NewString(tableName, "response_headers")
	_request.ResponseBody = field.NewString(tableName, "response_body")
	_request.StatusCode = field.NewInt(tableName, "status_code")
	_request.ResponseTime = field.NewInt(tableName, "response_time")
	_request.PromptTokens = field.NewInt(tableName, "prompt_tokens")
	_request.CompletionTokens = field.NewInt(tableName, "completion_tokens")
	_request.TotalTokens = field.NewInt(tableName, "total_tokens")
	_request.Cost = field.NewFloat64(tableName, "cost")
	_request.UserID = field.NewUint(tableName, "user_id")
	_request.APIKeyID = field.NewUint(tableName, "api_key_id")
	_request.ProviderID = field.NewUint(tableName, "provider_id")
	_request.ModelID = field.NewUint(tableName, "model_id")

	_request.fillFieldMap()

	return _request
}

type request struct {
	requestDo

	ALL              field.Asterisk
	ID               field.Uint
	CreatedAt        field.Time
	UpdatedAt        field.Time
	DeletedAt        field.Field
	Method           field.String
	Path             field.String
	RequestHeaders   field.String
	RequestBody      field.String
	ResponseHeaders  field.String
	ResponseBody     field.String
	StatusCode       field.Int
	ResponseTime     field.Int
	PromptTokens     field.Int
	CompletionTokens field.Int
	TotalTokens      field.Int
	Cost             field.Float64
	UserID           field.Uint
	APIKeyID         field.Uint
	ProviderID       field.Uint
	ModelID          field.Uint

	fieldMap map[string]field.Expr
}

func (r request) Table(newTableName string) *request {
	r.requestDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r request) As(alias string) *request {
	r.requestDo.DO = *(r.requestDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *request) updateTableName(table string) *request {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewUint(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")
	r.Method = field.NewString(table, "method")
	r.Path = field.NewString(table, "path")
	r.RequestHeaders = field.NewString(table, "request_headers")
	r.RequestBody = field.NewString(table, "request_body")
	r.ResponseHeaders = field.NewString(table, "response_headers")
	r.ResponseBody = field.NewString(table, "response_body")
	r.StatusCode = field.NewInt(table, "status_code")
	r.ResponseTime = field.NewInt(table, "response_time")
	r.PromptTokens = field.NewInt(table, "prompt_tokens")
	r.CompletionTokens = field.NewInt(table, "completion_tokens")
	r.TotalTokens = field.NewInt(table, "total_tokens")
	r.Cost = field.NewFloat64(table, "cost")
	r.UserID = field.NewUint(table, "user_id")
	r.APIKeyID = field.NewUint(table, "api_key_id")
	r.ProviderID = field.NewUint(table, "provider_id")
	r.ModelID = field.NewUint(table, "model_id")

	r.fillFieldMap()

	return r
}

func (r *request) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *request) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 20)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
	r.fieldMap["method"] = r.Method
	r.fieldMap["path"] = r.Path
	r.fieldMap["request_headers"] = r.RequestHeaders
	r.fieldMap["request_body"] = r.RequestBody
	r.fieldMap["response_headers"] = r.ResponseHeaders
	r.fieldMap["response_body"] = r.ResponseBody
	r.fieldMap["status_code"] = r.StatusCode
	r.fieldMap["response_time"] = r.ResponseTime
	r.fieldMap["prompt_tokens"] = r.PromptTokens
	r.fieldMap["completion_tokens"] = r.CompletionTokens
	r.fieldMap["total_tokens"] = r.TotalTokens
	r.fieldMap["cost"] = r.Cost
	r.fieldMap["user_id"] = r.UserID
	r.fieldMap["api_key_id"] = r.APIKeyID
	r.fieldMap["provider_id"] = r.ProviderID
	r.fieldMap["model_id"] = r.ModelID
}

func (r request) clone(db *gorm.DB) request {
	r.requestDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r request) replaceDB(db *gorm.DB) request {
	r.requestDo.ReplaceDB(db)
	return r
}

type requestDo struct{ gen.DO }

func (r requestDo) Debug() *requestDo {
	return r.withDO(r.DO.Debug())
}

func (r requestDo) WithContext(ctx context.Context) *requestDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r requestDo) ReadDB() *requestDo {
	return r.Clauses(dbresolver.Read)
}

func (r requestDo) WriteDB() *requestDo {
	return r.Clauses(dbresolver.Write)
}

func (r requestDo) Session(config *gorm.Session) *requestDo {
	return r.withDO(r.DO.Session(config))
}

func (r requestDo) Clauses(conds ...clause.Expression) *requestDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r requestDo) Returning(value interface{}, columns ...string) *requestDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r requestDo) Not(conds ...gen.Condition) *requestDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r requestDo) Or(conds ...gen.Condition) *requestDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r requestDo) Select(conds ...field.Expr) *requestDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r requestDo) Where(conds ...gen.Condition) *requestDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r requestDo) Order(conds ...field.Expr) *requestDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r requestDo) Distinct(cols ...field.Expr) *requestDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r requestDo) Omit(cols ...field.Expr) *requestDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r requestDo) Join(table schema.Tabler, on ...field.Expr) *requestDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r requestDo) LeftJoin(table schema.Tabler, on ...field.Expr) *requestDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r requestDo) RightJoin(table schema.Tabler, on ...field.Expr) *requestDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r requestDo) Group(cols ...field.Expr) *requestDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r requestDo) Having(conds ...gen.Condition) *requestDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r requestDo) Limit(limit int) *requestDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r requestDo) Offset(offset int) *requestDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r requestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *requestDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r requestDo) Unscoped() *requestDo {
	return r.withDO(r.DO.Unscoped())
}

func (r requestDo) Create(values ...*models.Request) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r requestDo) CreateInBatches(values []*models.Request, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r requestDo) Save(values ...*models.Request) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r requestDo) First() (*models.Request, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.Request), nil
	}
}

func (r requestDo) Take() (*models.Request, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.Request), nil
	}
}

func (r requestDo) Last() (*models.Request, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.Request), nil
	}
}

func (r requestDo) Find() ([]*models.Request, error) {
	result, err := r.DO.Find()
	return result.([]*models.Request), err
}

func (r requestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.Request, err error) {
	buf := make([]*models.Request, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r requestDo) FindInBatches(result *[]*models.Request, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r requestDo) Attrs(attrs ...field.AssignExpr) *requestDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r requestDo) Assign(attrs ...field.AssignExpr) *requestDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r requestDo) Joins(fields ...field.RelationField) *requestDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r requestDo) Preload(fields ...field.RelationField) *requestDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r requestDo) FirstOrInit() (*models.Request, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.Request), nil
	}
}

func (r requestDo) FirstOrCreate() (*models.Request, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.Request), nil
	}
}

func (r requestDo) FindByPage(offset int, limit int) (result []*models.Request, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r requestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r requestDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r requestDo) Delete(models ...*models.Request) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *requestDo) withDO(do gen.Dao) *requestDo {
	r.DO = *do.(*gen.DO)
	return r
}
