// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package consts

import (
	"fmt"
	"strings"
)

const (
	// ProviderOpenai is a Provider of type openai.
	ProviderOpenai Provider = "openai"
	// ProviderGemini is a Provider of type gemini.
	ProviderGemini Provider = "gemini"
	// ProviderIflow is a Provider of type iflow.
	ProviderIflow Provider = "iflow"
	// ProviderCodex is a Provider of type codex.
	ProviderCodex Provider = "codex"
)

var ErrInvalidProvider = fmt.Errorf("not a valid Provider, try [%s]", strings.Join(_ProviderNames, ", "))

var _ProviderNames = []string{
	string(ProviderOpenai),
	string(ProviderGemini),
	string(ProviderIflow),
	string(ProviderCodex),
}

// ProviderNames returns a list of possible string values of Provider.
func ProviderNames() []string {
	tmp := make([]string, len(_ProviderNames))
	copy(tmp, _ProviderNames)
	return tmp
}

// ProviderValues returns a list of the values for Provider
func ProviderValues() []Provider {
	return []Provider{
		ProviderOpenai,
		ProviderGemini,
		ProviderIflow,
		ProviderCodex,
	}
}

// String implements the Stringer interface.
func (x Provider) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Provider) IsValid() bool {
	_, err := ParseProvider(string(x))
	return err == nil
}

var _ProviderValue = map[string]Provider{
	"openai": ProviderOpenai,
	"gemini": ProviderGemini,
	"iflow":  ProviderIflow,
	"codex":  ProviderCodex,
}

// ParseProvider attempts to convert a string to a Provider.
func ParseProvider(name string) (Provider, error) {
	if x, ok := _ProviderValue[name]; ok {
		return x, nil
	}
	return Provider(""), fmt.Errorf("%s is %w", name, ErrInvalidProvider)
}

const (
	// ProviderPlatformAliyun is a ProviderPlatform of type aliyun.
	ProviderPlatformAliyun ProviderPlatform = "aliyun"
	// ProviderPlatformVolcengine is a ProviderPlatform of type volcengine.
	ProviderPlatformVolcengine ProviderPlatform = "volcengine"
	// ProviderPlatformGemini is a ProviderPlatform of type gemini.
	ProviderPlatformGemini ProviderPlatform = "gemini"
	// ProviderPlatformIflow is a ProviderPlatform of type iflow.
	ProviderPlatformIflow ProviderPlatform = "iflow"
	// ProviderPlatformOpenai is a ProviderPlatform of type openai.
	ProviderPlatformOpenai ProviderPlatform = "openai"
	// ProviderPlatformDeepseek is a ProviderPlatform of type deepseek.
	ProviderPlatformDeepseek ProviderPlatform = "deepseek"
	// ProviderPlatformCodex is a ProviderPlatform of type codex.
	ProviderPlatformCodex ProviderPlatform = "codex"
	// ProviderPlatformAntigravity is a ProviderPlatform of type antigravity.
	ProviderPlatformAntigravity ProviderPlatform = "antigravity"
)

var ErrInvalidProviderPlatform = fmt.Errorf("not a valid ProviderPlatform, try [%s]", strings.Join(_ProviderPlatformNames, ", "))

var _ProviderPlatformNames = []string{
	string(ProviderPlatformAliyun),
	string(ProviderPlatformVolcengine),
	string(ProviderPlatformGemini),
	string(ProviderPlatformIflow),
	string(ProviderPlatformOpenai),
	string(ProviderPlatformDeepseek),
	string(ProviderPlatformCodex),
	string(ProviderPlatformAntigravity),
}

// ProviderPlatformNames returns a list of possible string values of ProviderPlatform.
func ProviderPlatformNames() []string {
	tmp := make([]string, len(_ProviderPlatformNames))
	copy(tmp, _ProviderPlatformNames)
	return tmp
}

// ProviderPlatformValues returns a list of the values for ProviderPlatform
func ProviderPlatformValues() []ProviderPlatform {
	return []ProviderPlatform{
		ProviderPlatformAliyun,
		ProviderPlatformVolcengine,
		ProviderPlatformGemini,
		ProviderPlatformIflow,
		ProviderPlatformOpenai,
		ProviderPlatformDeepseek,
		ProviderPlatformCodex,
		ProviderPlatformAntigravity,
	}
}

// String implements the Stringer interface.
func (x ProviderPlatform) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ProviderPlatform) IsValid() bool {
	_, err := ParseProviderPlatform(string(x))
	return err == nil
}

var _ProviderPlatformValue = map[string]ProviderPlatform{
	"aliyun":     ProviderPlatformAliyun,
	"volcengine": ProviderPlatformVolcengine,
	"gemini":     ProviderPlatformGemini,
	"iflow":      ProviderPlatformIflow,
	"openai":     ProviderPlatformOpenai,
	"deepseek":   ProviderPlatformDeepseek,
	"codex":      ProviderPlatformCodex,
	"antigravity": ProviderPlatformAntigravity,
}

// ParseProviderPlatform attempts to convert a string to a ProviderPlatform.
func ParseProviderPlatform(name string) (ProviderPlatform, error) {
	if x, ok := _ProviderPlatformValue[name]; ok {
		return x, nil
	}
	return ProviderPlatform(""), fmt.Errorf("%s is %w", name, ErrInvalidProviderPlatform)
}
