DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS providers;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS settings;
DROP INDEX IF EXISTS idx_users_email_unique;