-- Add OAuth2 fields to providers table
ALTER TABLE providers 
ADD COLUMN IF NOT EXISTS client_id VARCHAR(255),
ADD COLUMN IF NOT EXISTS client_secret VARCHAR(255),
ADD COLUMN IF NOT EXISTS access_token TEXT,
ADD COLUMN IF NOT EXISTS refresh_token TEXT,
ADD COLUMN IF NOT EXISTS token_expiry TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS auth_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS token_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS redirect_url VARCHAR(255),
ADD COLUMN IF NOT EXISTS scopes TEXT;
